In [1]:
import numpy as np

Creating Arrays

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(6, 10)

array([6, 7, 8, 9])

In [29]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi-diemnsional arrays

In [30]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
md_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [46]:
md_arr[2] = [4, 5, 6]
md_arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [47]:
md_arr[0, 2]

3

In [57]:
md_arr[:, 2]

array([3, 6, 6])

Randomly generated arrays

In [74]:
np.random.seed(2)
100*np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [78]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [80]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [91]:
b = a * 10
b

array([ 0, 10, 20, 30, 40])

Comparison operations 

In [84]:
a

array([0, 1, 2, 3, 4])

In [86]:
a >= 2

array([False, False,  True,  True,  True])

In [93]:
a >= b

array([ True, False, False, False, False])

In [94]:
a[a >= b]


array([0])

Summarizing operations

In [103]:
a.mean()

2.0